### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by fverrierpaquette** [ReCONstruct-Digital-Platform/Building-Identification-Tool#1]
(writing this issue as a test): Certainty rating system could be on a scale of 1-5, with 1 being certainty that the building is not metal, and 5 being certainty that the building is metal. The current system (yes, maybe, no) does not allow for effective classification of photos for group review.

**Comment by sharon0326** [comment]
I have updated the latest version of Image-Tool. 
Open in CHROME: http://sharonshen66.pythonanywhere.com/ 
New features:
1, add a selection slider on a scale of 1 to 5.
2, only panoramas are displayed. (5 addresses as a test)
3, a zoom in section beneath the panorama.

**Comment by fverrierpaquette** [comment]
I think the functionality is great, really well done!! :) The zoom callout works really well. I'm wondering if the submit button can automatically bring us to the next image, instead of manually having to navigate to image classification-->image number?

**Comment by sharon0326** [comment]
The submit button should work right now!
Add: No, this feature does not work 24/7. It only works when my console's open...It's not always-on tasks.

**Comment by fverrierpaquette** [comment]
Ok that makes sense about your console, eventually I guess it would be on a server? Also Thomas and I were chatting, and we think it might be more intuitive to have 5 selection boxes (1,2,3,4,5) instead of a slider with 5 positions? I think the definitions could be written next to the boxes as well, so next to box #1 would be "definitely not metal", box #2 is "pretty sure not metal" box #3 is "unsure", box #4 is "pretty sure metal" and next to box #5 would be "definitely metal" It's a minor change, they both work, but it will be more comfortable that way :)

Edit: We also think it would be useful to have the address display next to the image, as a link that would open google maps in case someone wants to go see for themselves on their browser. That can definitely be a later addition though!!!

Edit #2: Would it be possible to have the image ID displayed prominently next to the image?

**Comment by sharon0326** [comment]
The ID can be definitely displayed next to the image! 
It should be possible to display the address as well, but let me think about how to achieve it before I come back to you. 

For the selection box, because of the space constraint (we have a lot info to display on the left bottom corner 😂), I feel like we need to choose between the description section and 5 selection boxes, i.e., either keep the description section "Rate the picture on a scale of 1-5..." or keep the 5 selection boxes and move the description section to the front page or elsewhere. Otherwise, I have the concern that people need to scroll down the webpage to see all the information which will decrease the selection efficiency.

**Comment by fverrierpaquette** [comment]
![image](https://user-images.githubusercontent.com/114252919/219791223-6006f1fd-a3b6-43f8-b72d-eb5e1baa5211.png)
I had pictured it something like this, I'm not sure if it's because I'm viewing it on a larger screen?

**Comment by sharon0326** [comment]
<img width="959" alt="1" src="https://user-images.githubusercontent.com/74162602/219792722-ee1eea03-7c21-414e-a095-8dd63d2fe898.png">


Yeah, you probably have a larger screen than mine. Than's what I see 😂.
Let me think if I can make the web fluid or not.

**Comment by sharon0326** [comment]
Maybe it’s a bit earlier to discuss at this stage. As Zainab mentioned in last meeting, if we may use machine learning method to classify images, I am wondering what are some specular characteristics of metal building: being white, with a steeple like top, or else?

I have come across three papers in the weekend, and I am also wondering if some of these below covered the concept of “metal building”, especially the third paper: 
1)	Classify apartment, church, house and industrial: 
https://www150.statcan.gc.ca/n1/pub/18-001-x/18-001-x2021003-eng.htm
2)	Classify concrete, brick, metal, wood, and stone on a micro scale:
https://www.sciencedirect.com/science/article/pii/S0921344922002075
3)	Classify FEMA building such as: Steel moment-resisting frame, Braced steel frame, Light metal building, Steel frames with cast-in-place concrete shear walls, Steel frames with unreinforced masonry infill walls, and etc. 
https://www.tandfonline.com/doi/full/10.1080/23311916.2022.2065900

And since no matter what, we will do a lot of manual work at the initial stage, why not add some other tags to the image? Like, residential building, road and etc., and train them all at the training stage.

**Comment by sharon0326** [comment]
A quick update regarding the host. Unfortunately, I did not hear a positive feedback from IT service. So, I share my PythonAnywhere account with Chloe and Loic and continue the development from there.

**Comment by fverrierpaquette** [comment]
Thanks for letting us know! Will you want to get a monthly for PythonAnywhere, and if so which plan would you need?

**Comment by sharon0326** [comment]
I would like to customize the plan instead, and prioritize "disk space" and "always on task". 
<img width="443" alt="屏幕截图(200)" src="https://user-images.githubusercontent.com/74162602/224562334-2f702ec2-c721-45b7-a366-244c7950e0d1.png">

**Comment by fverrierpaquette** [comment]
Thanks laying out all the criteria! I'll show it to Frank and we'll get back to you ASAP!

**Comment by sharon0326** [comment]
Thanks for the feedback, from your email I also aware that PythonAnywhere may not be a certified cloud service by McGill. Already sent an inquiry request.
